credentials_file = ''
spreadsheet_id = ''
scopes = ['']
apps_url = 'http://node.brightid.org/brightid/v5/apps'
linked_users_url_v5 = 'http://node.brightid.org/brightid/v5/verifications/{}?count_only'
linked_users_url_v6 = 'http://node.brightid.org/brightid/v6/verifications/{}?countOnly=true&period={}'
data_file_addr = '../ui/apps.json'
token_file_addr = ''
sponsoreds_snapshot_period = 86400
